# Generated by Django 6.1.1 on 2026-09-18 10:30

from django.db import migrations

def assign_group_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    landlord = Group.objects.get(name='Landlord')
    tenant = Group.objects.get(name='Tenant')

    # Права для Landlord — управление объявлениями
    landlord_permissions = Permission.objects.filter(
        codename__in=[
            'add_listing', 'change_listing', 'delete_listing', 'view_listing',
            'add_listingimage', 'change_listingimage', 'delete_listingimage', 'view_listingimage',
            'view_booking', 'change_booking',
            'view_review',
        ]
    )
    landlord.permissions.set(landlord_permissions)

    # Права для Tenant — просмотр и бронирование
    tenant_permissions = Permission.objects.filter(
        codename__in=[
            'view_listing', 'view_listingimage',
            'add_booking', 'view_booking', 'delete_booking',
            'add_review', 'view_review', 'change_review', 'delete_review',
        ]
    )
    tenant.permissions.set(tenant_permissions)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20260915_1305'),
    ]

    operations = [
        migrations.RunPython(assign_group_permissions),
    ]
