
services:
  db:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:

      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL: "True"
      DB_HOST: db
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
    depends_on:
      db:

        condition: service_healthy

#  frontend:
#    build:
#      context: ../rental-frontend
#    container_name: rental-frontend
#    restart: unless-stopped
#    environment:
#      VITE_BACKEND_URL: http://web:8000
#    ports:
#      - "5173:5173"
#    depends_on:
#      - web
#    volumes:
#      - ../rental-frontend:/app
#      - /app/node_modules

volumes:
  mysql_data: