# Generated by Django 6.1.1 on 2026-09-22 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_initial'),
        ('listings', '0004_alter_listing_owner_listing_listing_location_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewhistory',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='views', to='listings.listing'),
        ),
    ]
