# Generated by Django 6.1.1 on 2026-09-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('in_progress', 'в процессе'), ('approved', 'одобрено'), ('rejected', 'отклоненно')], default='in_progress', max_length=15),
        ),
    ]
