# Generated by Django 6.1.1 on 2026-09-22 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_status'),
        ('listings', '0004_alter_listing_owner_listing_listing_location_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('in_progress', 'в процессе'), ('approved', 'одобрено'), ('rejected', 'отклоненно'), ('cancelled', 'отменено арендатором')], default='in_progress', max_length=15),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['listing', 'date_from', 'date_to'], name='booking_listing_dates_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['tenant', 'status'], name='booking_tenant_status_idx'),
        ),
    ]
