# Generated by Django 6.1.1 on 2026-09-22 12:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_status_alter_booking_tenant_and_more'),
        ('listings', '0004_alter_listing_owner_listing_listing_location_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('status', 'cancelled'), _negated=True), models.Q(('status', 'rejected'), _negated=True)), fields=('tenant', 'listing', 'date_from', 'date_to'), name='unique_active_booking'),
        ),
    ]
